=== miki995/XML-schema/XmlSchemaWebShop.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="product_type">
        <xs:sequence>
            <xs:element name="productName" type="xs:string"/>
            <xs:element name="productDescription" type="xs:string"/>
            <xs:element name="productPrice" type="xs:float"/>
            <xs:element name="productUrl" type="xs:string"/>
            <xs:element name="productDateAvailable" type="xs:date"/>
            <xs:element name="productChangeDate" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="manufacturerId" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="productImage_type">
        <xs:sequence>
            <xs:element name="image" type="xs:string"/>
            <xs:element name="hTMLContent" type="xs:string"/>
            <xs:element name="imageSortOrder" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="productImageId" type="xs:ID" use="required"/>
        <xs:attribute name="productId" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="manufacturer_type">
        <xs:sequence>
            <xs:element name="manufacturerName" type="xs:string"/>
            <xs:element name="manufacturerLogo" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="manufacturerId" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="productSpecial_type">
        <xs:sequence>
            <xs:element name="newProductPrice" type="xs:float"/>
            <xs:element name="startDate" type="xs:date"/>
            <xs:element name="expiryDate" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="promotionCode" type="xs:ID" use="required"/>
        <xs:attribute name="productId" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="customer_type">
        <xs:sequence>
            <xs:element name="gender" type="xs:boolean"/>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="middleName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="birthDate" type="xs:date"/>
            <xs:element name="emailAddress" type="xs:string"/>
            <xs:element name="phoneNumber" type="xs:string"/>
            <xs:element name="faxNumber" type="xs:string"/>
            <xs:element name="password" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="customerId" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="address_type">
        <xs:sequence>
            <xs:element name="addressFromDate" type="xs:date"/>
            <xs:element name="addressToDate" type="xs:date"/>
            <xs:element name="addressStreet" type="xs:string"/>
            <xs:element name="ZipCode" type="xs:int"/>
            <xs:element name="addressType" type="xs:string"/>

        </xs:sequence>
        <xs:attribute name="addressId" type="xs:ID" use="required"/>
        <xs:attribute name="customerId" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="order_type">
        <xs:sequence>
            <xs:element name="reference" type="xs:string"/>
            <xs:element name="billingName" type="xs:string"/>
            <xs:element name="deliveryName" type="xs:string"/>
            <xs:element name="emailAddress" type="xs:string"/>
            <xs:element name="purchaseDate" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="orderId" type="xs:ID" use="required"/>
        <xs:attribute name="customerId" type="xs:IDREF" use="required"/>
        <xs:attribute name="addressId" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="orderStatus_type">
        <xs:sequence>
            <xs:element name="orderStatusDescription" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="OrderStatusCode" type="xs:ID" use="required"/>
    </xs:complexType>


    <xs:complexType name="orderedProduct_type">
        <xs:sequence>
            <xs:element name="productName" type="xs:string"/>
            <xs:element name="productDescription" type="xs:string"/>
            <xs:element name="productPrice" type="xs:float"/>
            <xs:element name="productTax" type="xs:float"/>
            <xs:element name="quantity" type="xs:int"/>
        </xs:sequence>
        <xs:attribute name="orderedProductId" type="xs:ID" use="required"/>
        <xs:attribute name="productId" type="xs:IDREF" use="required"/>
        <xs:attribute name="orderId" type="xs:IDREF" use="required"/>
    </xs:complexType>


    <xs:complexType name="review_type">
        <xs:sequence>
            <xs:element name="reviewRating" type="xs:int"/>
            <xs:element name="reviewReads" type="xs:string"/>
            <xs:element name="ReviewText" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="reviewId" type="xs:ID" use="required"/>
        <xs:attribute name="customerId" type="xs:IDREF" use="required"/>
        <xs:attribute name="productId" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="basket_type">
        <xs:sequence>
            <xs:element name="basketDateAdded" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="basketId" type="xs:ID" use="required"/>
        <xs:attribute name="customerId" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="basketStatus_type">
        <xs:sequence>
            <xs:element name="basketStatusDescription" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="basketStatusCode" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="basketProduct_type">
        <xs:sequence>
            <xs:element name="quantity" type="xs:int"/>
        </xs:sequence>
        <xs:attribute name="basketId" type="xs:IDREF" use="required"/>
        <xs:attribute name="productId" type="xs:IDREF" use="required"/>
    </xs:complexType>



    <xs:complexType name="webShop_type">
        <xs:sequence>

            <xs:element name="products">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="product" type="product_type" maxOccurs="unbounded">
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="productImages">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="productImage" type="productImage_type"
                            maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>


            <xs:element name="productSpecials">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="productSpecial" type="productSpecial_type"
                            maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="manufacturers">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="manufacturer" type="manufacturer_type"
                            maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>


            <xs:element name="customers">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="customer" type="customer_type" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="orders">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="order" type="order_type" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>


            <xs:element name="orderedProducts">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="orderedProduct" type="orderedProduct_type"
                            maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="reviews">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="review" type="review_type" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="addresses">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="address" type="address_type" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="baskets">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="basket" type="basket_type" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="basketProducts">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="basketProduct" type="basketProduct_type"
                            maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="webShop" type="webShop_type"/>

</xs:schema>

=== miki995/XML-schema/xmlWebShopGenerated.xml
<?xml version="1.0" encoding="UTF-8"?>
<webShop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/S/Desktop/Studies/Primary%20%20subjects/XML/3rd%20class/XmlSchemaWebShop.xsd">
    <products>
    <product id="pi11" manufacturerId="m1">
        <productName>amazon echo</productName>
        <productDescription>speaker</productDescription>
        <productPrice>12</productPrice>
        <productUrl>http://something</productUrl>
        <productDateAvailable>2017-04-09</productDateAvailable>
        <productChangeDate>2017-04-09</productChangeDate>
    </product>
    <product id="pi12" manufacturerId="m1">
        <productName>amazon echo</productName>
        <productDescription>speaker</productDescription>
        <productPrice>12</productPrice>
        <productUrl>http://something</productUrl>
        <productDateAvailable>2017-04-09</productDateAvailable>
        <productChangeDate>2017-04-09</productChangeDate>
    </product>
    </products>
    <productImages>
    <productImage productImageId="pi1" productId="pi11">
        <image>asnsaddi</image>
        <hTMLContent>http://abudavi</hTMLContent>
        <imageSortOrder>date</imageSortOrder>
    </productImage>
    <productImage productImageId="pi2" productId="pi12">
        <image>asndi</image>
        <hTMLContent>http://soemtas</hTMLContent>
        <imageSortOrder>time</imageSortOrder>
    </productImage>
    </productImages>
  
    <productSpecials>
    <productSpecial promotionCode="pc1" productId="pi11">
        <newProductPrice>12</newProductPrice>
        <startDate>2017-04-09</startDate>
        <expiryDate>2017-04-09</expiryDate>
    </productSpecial>
        <productSpecial promotionCode="pc2" productId="pi12">
            <newProductPrice>15</newProductPrice>
            <startDate>2017-04-09</startDate>
            <expiryDate>2017-04-09</expiryDate>
        </productSpecial>
    </productSpecials>
    
    <manufacturers>
        <manufacturer manufacturerId="m1">
            <manufacturerName>Amazon</manufacturerName>
            <manufacturerLogo>http://somethin</manufacturerLogo>
        </manufacturer>
        <manufacturer manufacturerId="m2">
            <manufacturerName>Google</manufacturerName>
            <manufacturerLogo>http://gogol</manufacturerLogo>
        </manufacturer>
    </manufacturers>
    
        <customers>
    <customer customerId="ci1">
        <gender>1</gender>
        <firstName>Miroslav</firstName>
        <middleName>Miki</middleName>
        <lastName>Maksimovic</lastName>
        <birthDate>2000-04-09</birthDate>
        <emailAddress>mirki@gmail.com</emailAddress>
        <phoneNumber>232141</phoneNumber>
        <faxNumber>2134214</faxNumber>
        <password>ansdmoe1423</password>
    </customer>
    <customer customerId="ci2">
        <gender>1</gender>
        <firstName>Tomo</firstName>
        <middleName>Tom</middleName>
        <lastName>Klacar</lastName>
        <birthDate>2000-04-09</birthDate>
        <emailAddress>tomo@gmail.com</emailAddress>
        <phoneNumber>242342</phoneNumber>
        <faxNumber>241342</faxNumber>
        <password>eofk342sd</password>
    </customer>
        </customers>
    <orders>
    <order orderId="oi1" customerId="ci1" addressId="ai1">
        <reference>echo</reference>
        <billingName>Miroslav</billingName>
        <deliveryName>miroslav</deliveryName>
        <emailAddress>asdmi@gmail.com</emailAddress>
        <purchaseDate>2017-09-04</purchaseDate>
    </order>
    <order orderId="oi2" customerId="ci2" addressId="ai1">
        <reference>home</reference>
        <billingName>Tomo</billingName>
        <deliveryName>tomo</deliveryName>
        <emailAddress>asdmi@gmail.com</emailAddress>
        <purchaseDate>2017-09-04</purchaseDate>
    </order>
    </orders>
    <orderedProducts>
    <orderedProduct orderedProductId="opi1" productId="pi1" orderId="oi1">
        <productName>echo</productName>
        <productDescription>speaker</productDescription>
        <productPrice>12</productPrice>
        <productTax>11</productTax>
        <quantity>23</quantity>
    </orderedProduct>
    <orderedProduct orderedProductId="opi2" productId="pi12" orderId="oi2">
        <productName>amazon</productName>
        <productDescription>home</productDescription>
        <productPrice>12</productPrice>
        <productTax>11</productTax>
        <quantity>23</quantity>
    </orderedProduct>
    </orderedProducts>
    <reviews>
    <review reviewId="ri1" customerId="ci1" productId="pi1">
        <reviewRating>10</reviewRating>
        <reviewReads>10</reviewReads>
        <ReviewText>nice</ReviewText>
    </review>
    <review reviewId="ri2" customerId="ci2" productId="pi12">
        <reviewRating>6</reviewRating>
        <reviewReads>5</reviewReads>
        <ReviewText>bad</ReviewText>
    </review>
    </reviews>
    <addresses>
    <address addressId="ai1" customerId="ci1">
        <addressFromDate>2000-04-09</addressFromDate>
        <addressToDate>2000-04-09</addressToDate>
        <addressStreet>bosnia</addressStreet>
        <ZipCode>73300</ZipCode>
        <addressType>flat</addressType>
    </address>
    <address addressId="ai2" customerId="ci2">
        <addressFromDate>2000-04-09</addressFromDate>
        <addressToDate>2000-04-09</addressToDate>
        <addressStreet>hungary</addressStreet>
        <ZipCode>3515</ZipCode>
        <addressType>house</addressType>
    </address>
    </addresses>
   
    <baskets>
    <basket basketId="bi1" customerId="ci1">
        <basketDateAdded>2000-04-09</basketDateAdded>
    </basket>
    <basket basketId="bi2" customerId="ci2">
        <basketDateAdded>2000-04-09</basketDateAdded>
    </basket>
    </baskets>
    <basketProducts>
    <basketProduct basketId="bi1" productId="pi11">
        <quantity>4</quantity>
    </basketProduct>
    <basketProduct basketId="bi2" productId="pi12">
        <quantity>10</quantity>
    </basketProduct>
    </basketProducts>
</webShop>
